# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

import img_rc

from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia

from AudioIterator import AudioIterator


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """Constructor window form"""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 681)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background: #646464")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetMaximumSize
        )
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.picture = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture.sizePolicy().hasHeightForWidth())
        self.picture.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        self.picture.setFont(font)
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap(":/img/img_plast.png"))
        self.picture.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.picture.setObjectName("picture")
        self.verticalLayout.addWidget(self.picture)
        self.track_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        self.track_title.setFont(font)
        self.track_title.setMidLineWidth(0)
        self.track_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.track_title.setObjectName("track_title")
        self.verticalLayout.addWidget(self.track_title)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setMaximum(9999)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.prev_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_button.sizePolicy().hasHeightForWidth())
        self.prev_button.setSizePolicy(sizePolicy)
        self.prev_button.setStyleSheet("background: #808080")
        self.prev_button.setText("")
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(
            QtGui.QPixmap(":/img/iter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.prev_button.setIcon(self.icon)
        self.prev_button.setIconSize(QtCore.QSize(30, 30))
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout_4.addWidget(self.prev_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setStyleSheet("background: #808080")
        self.stop_button.setText("")
        self.icon1 = QtGui.QIcon()
        self.icon1.addPixmap(
            QtGui.QPixmap(":/img/Pause-Transparent.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.icon2 = QtGui.QIcon()
        self.icon2.addPixmap(
            QtGui.QPixmap(":/img/play.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.stop_button.setIcon(self.icon1)
        self.stop_button.setIconSize(QtCore.QSize(35, 35))
        self.stop_button.setCheckable(False)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_4.addWidget(self.stop_button)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setAutoFillBackground(False)
        self.next_button.setStyleSheet("background: #808080")
        self.next_button.setText("")
        self.icon3 = QtGui.QIcon()
        self.icon3.addPixmap(
            QtGui.QPixmap(":/img/iter2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.next_button.setIcon(self.icon3)
        self.next_button.setIconSize(QtCore.QSize(30, 30))
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_4.addWidget(self.next_button)
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setMaximumSize(QtCore.QSize(200, 50))
        self.volume_slider.setMaximum(100)
        self.volume_slider.setValue(100)
        self.volume_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout_4.addWidget(self.volume_slider)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.mediaplayer = QtMultimedia.QMediaPlayer()

        self.__is_play = False
        self.__picFlag = False

        self.mediaplayer.durationChanged.connect(self.__initSlider)
        self.mediaplayer.durationChanged.connect(self.__durationDisplay)
        self.mediaplayer.mediaStatusChanged.connect(self.__handleStatus)
        self.horizontalSlider.sliderMoved.connect(self.__rewindTo)
        self.volume_slider.valueChanged.connect(self.__setVolume)
        self.mediaplayer.positionChanged.connect(self.__showWhilePlay)
        self.next_button.clicked.connect(self.__nextTrack)
        self.prev_button.clicked.connect(self.__prevTrack)

        self.stop_button.clicked.connect(self.__play)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AudioPlayer2.0"))
        self.title.setText(_translate("MainWindow", "SUPER MEGA AUDIO PLAYER 2.0"))
        self.track_title.setText(_translate("MainWindow", "TRACK NAME"))

    def __handleStatus(self, status):
        """Play next audio if this was ended"""
        if status == QtMultimedia.QMediaPlayer.EndOfMedia:
            self.__nextTrack()
            self.horizontalSlider.setEnabled(False)
            self.__play()
            self.horizontalSlider.setEnabled(True)

    def __initSlider(self, duration_ms):
        """Set end value of the slider on audio file duration"""
        self.horizontalSlider.setMaximum(duration_ms)

    def __rewindTo(self, pos):
        """Set position in audio file if slider was moved"""
        self.mediaplayer.setPosition(pos)

    def __setVolume(self, val):
        """Set volume if volume slider was moved"""
        self.mediaplayer.setVolume(val)

    def __play(self):
        """Play or pause audio when clicked on button"""
        if not self.__is_play:
            self.mediaplayer.play()
            self.stop_button.setIcon(self.icon2)
            self.__is_play = True
        else:
            self.mediaplayer.pause()
            self.stop_button.setIcon(self.icon1)
            self.__is_play = False

    def __showWhilePlay(self, position):
        """Show vizual feauters while audio is playing"""
        self.horizontalSlider.setValue(position)
        if self.__is_play:
            if self.__picFlag:
                self.picture.setPixmap(QtGui.QPixmap(":/img/img_plast.png"))
            else:
                self.picture.setPixmap(QtGui.QPixmap(":/img/img_plast2.png"))
            self.__picFlag = not self.__picFlag

    def set_audio_iterator(self, iterator: AudioIterator):
        """Get iterator for audio directory"""
        self.iterator = iterator
        self.track = self.iterator.cur()
        self.__setTrack()

    def __durationDisplay(self, duration):
        """Display audio name and duration"""
        total_seconds = duration // 1000
        minutes = total_seconds // 60
        seconds = total_seconds % 60
        self.track_title.setText(
            str(os.path.basename(self.track) + f" ({minutes:02d}:{seconds:02d})")
        )

    def __setTrack(self):
        """Reset settings if track was changed"""
        self.mediaplayer.stop()
        self.stop_button.setIcon(self.icon1)
        self.horizontalSlider.setValue(0)
        self.mediaplayer.setPosition(0)
        self.mediaplayer.setMedia(
            QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile(self.track))
        )

    def __nextTrack(self):
        """Get next track by iterator"""
        try:
            self.track = next(self.iterator)
        except StopIteration:
            pass
        self.__setTrack()
        self.__is_play = not self.__is_play
        self.__play()

    def __prevTrack(self):
        """Get previous track by iterator"""
        try:
            self.track = self.iterator.prev()
        except StopIteration:
            pass
        self.__setTrack()
        self.__is_play = not self.__is_play
        self.__play()
