# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import rec
from Iterator import ImageIterator


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(388, 349)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background: #303030")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture.sizePolicy().hasHeightForWidth())
        self.picture.setSizePolicy(sizePolicy)
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap(":/images/fon.jpg"))
        self.picture.setAlignment(QtCore.Qt.AlignCenter)
        self.picture.setObjectName("picture")
        self.verticalLayout_2.addWidget(self.picture)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setStyleSheet("background: #a0a0a0")
        self.select_button.setObjectName("select_button")
        self.horizontalLayout.addWidget(self.select_button)
        self.prev_button = QtWidgets.QPushButton(self.centralwidget)
        self.prev_button.setStyleSheet("background: #a0a0a0")
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout.addWidget(self.prev_button)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setStyleSheet("background: #a0a0a0")
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.select_button.clicked.connect(self.open_folder)
        self.next_button.clicked.connect(self.show_next)
        self.prev_button.clicked.connect(self.show_prev)

        self.main_window = MainWindow
        self.current_image_path = None


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Просмотр изображений"))
        self.select_button.setText(_translate("MainWindow", "Выбрать папку..."))
        self.prev_button.setText(_translate("MainWindow", "Предыдущий"))
        self.next_button.setText(_translate("MainWindow", "Следующий"))

    def open_folder(self):
        """Открытие папки с изображениями"""
        folder = QtWidgets.QFileDialog.getExistingDirectory(
            caption="Выберите папку с изображениями"
        )

        if folder:
            self.current_folder = folder
            try:
                self.it = ImageIterator(self.current_folder)
                if len(self.it.paths) > 0:
                    self.current_image_path = self.it.paths[0]
                    self.update_image_display()
                else:
                    self.current_image_path = None
                    self.show_default_image()
            except:
                self.current_image_path = None
                self.it = None
                self.show_default_image()

    def show_next(self):
        """Показать следующее изображение"""
        if not hasattr(self, 'it') or self.it is None:
            return

        try:
            image = next(self.it)
            self.current_image_path = image
            self.update_image_display()
        except (StopIteration, AttributeError):
            return

    def show_prev(self):
        """Показать предыдущее изображение"""
        if not hasattr(self, 'it') or self.it is None:
            return

        try:
            image = self.it.prev()
            self.current_image_path = image
            self.update_image_display()
        except (StopIteration, AttributeError):
            return

    def update_image_display(self):
        """Обновляет отображение изображения с масштабированием под размер окна"""
        if not self.current_image_path:
            self.show_default_image()
            return

        pixmap = QtGui.QPixmap(self.current_image_path)
        if pixmap.isNull():
            self.show_default_image()
            return

        label_size = self.picture.size()
        max_width = label_size.width()
        max_height = label_size.height()

        scaled_pixmap = pixmap.scaled(
            max_width,
            max_height,
            QtCore.Qt.KeepAspectRatio,
            QtCore.Qt.SmoothTransformation
        )

        self.picture.setPixmap(scaled_pixmap)

    def show_default_image(self):
        """Показывает изображение по умолчанию (фон)"""
        pixmap = QtGui.QPixmap(":/images/fon.jpg")
        if not pixmap.isNull():
            label_size = self.picture.size()
            max_width = label_size.width()
            max_height = label_size.height()

            scaled_pixmap = pixmap.scaled(
                max_width,
                max_height,
                QtCore.Qt.KeepAspectRatio,
                QtCore.Qt.SmoothTransformation
            )
            self.picture.setPixmap(scaled_pixmap)

    def resizeEvent(self, event):
        """Обработчик изменения размера окна"""
        if hasattr(self, 'current_image_path') and self.current_image_path:
            self.update_image_display()
        else:
            self.show_default_image()
        super(type(self.main_window), self.main_window).resizeEvent(event)


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        QtCore.QTimer.singleShot(100, self.ui.show_default_image)


    def resizeEvent(self, event):
        """Изменение размера"""
        self.ui.resizeEvent(event)
        super().resizeEvent(event)
