import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from main_window import Ui_MainWindow
from load_images import parse_args, download_images, create_annotation, FileIterator
# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
class Window(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.prev_button.clicked.connect(self.on_prev)
        self.ui.next_button.clicked.connect(self.on_next)
        self.ui.folder_button.clicked.connect(self.on_folder)
        self.ui.annotation_button.clicked.connect(self.on_annotation)


    def on_prev(self):
        print("on_prev")

    def on_next(self):
        print("on_next")

    def on_folder(self):
        print("on_folder")

    def on_annotation(self):
        print("on_annotation")        




def main():
    try:

        app = QtWidgets.QApplication([])
        main_window = Window()

        main_window.show()
        sys.exit(app.exec())
    except Exception as e:
        print(f"Произошла ошибка: {e}")


if __name__ == "__main__":
    main()
