# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 896)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(2560, 1440))
        MainWindow.setStyleSheet("background-color: rgb(242, 243, 245);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(212, 210, 206, 255), stop:0.474576 rgba(178, 190, 190, 255), stop:1 rgba(212, 210, 206, 255));\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.source_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.source_widget.setStyleSheet("background-color: None;")
        self.source_widget.setObjectName("source_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.source_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folder_button = QtWidgets.QPushButton(parent=self.source_widget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.folder_button.setFont(font)
        self.folder_button.setStyleSheet("background-color: rgba(150, 153, 151, 200);\n"
"color: rgb(242, 243, 245);\n"
"border: 1px solid rgb(242, 243, 245);\n"
"border-radius: 4px;\n"
"padding: 3px")
        self.folder_button.setObjectName("folder_button")
        self.horizontalLayout.addWidget(self.folder_button)
        self.annotation_button = QtWidgets.QPushButton(parent=self.source_widget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.annotation_button.setFont(font)
        self.annotation_button.setStyleSheet("background-color: rgba(150, 153, 151, 200);\n"
"color: rgb(242, 243, 245);\n"
"border: 1px solid rgb(242, 243, 245);\n"
"border-radius: 4px;\n"
"padding: 3px")
        self.annotation_button.setObjectName("annotation_button")
        self.horizontalLayout.addWidget(self.annotation_button)
        self.verticalLayout_4.addWidget(self.source_widget)
        self.image_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.image_widget.setObjectName("image_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.image_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prev_button = QtWidgets.QPushButton(parent=self.image_widget)
        self.prev_button.setMinimumSize(QtCore.QSize(32, 32))
        self.prev_button.setMaximumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(30)
        font.setBold(True)
        self.prev_button.setFont(font)
        self.prev_button.setStyleSheet("color: rgb(242, 243, 245);\n"
"border: 1px solid rgb(242, 243, 245);\n"
"border-radius: 6px;\n"
"padding: 5px 12px;\n"
"background-color: None;")
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout_3.addWidget(self.prev_button)
        self.img = QtWidgets.QLabel(parent=self.image_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img.sizePolicy().hasHeightForWidth())
        self.img.setSizePolicy(sizePolicy)
        self.img.setMinimumSize(QtCore.QSize(64, 64))
        self.img.setStyleSheet("color: rgb(242, 243, 245);\n"
"background-color: None;")
        self.img.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.img.setObjectName("img")
        self.horizontalLayout_3.addWidget(self.img)
        self.next_button = QtWidgets.QPushButton(parent=self.image_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setMinimumSize(QtCore.QSize(32, 32))
        self.next_button.setMaximumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.next_button.setFont(font)
        self.next_button.setStyleSheet("color: rgb(242, 243, 245);\n"
"border: 1px solid rgb(242, 243, 245);\n"
"border-radius: 6px;\n"
"padding: 5px 12px;\n"
"background-color: None;")
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_3.addWidget(self.next_button)
        self.verticalLayout_4.addWidget(self.image_widget)
        self.info_widget = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_widget.sizePolicy().hasHeightForWidth())
        self.info_widget.setSizePolicy(sizePolicy)
        self.info_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.info_widget.setStyleSheet("background-color: rgba(150, 153, 151, 200);\n"
"border-radius: 4px;\n"
"padding: 0px;\n"
"margin:0px")
        self.info_widget.setObjectName("info_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.info_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.index = QtWidgets.QLabel(parent=self.info_widget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        self.index.setFont(font)
        self.index.setStyleSheet("color: rgb(242, 243, 245);\n"
"background-color: None;\n"
"padding: 1px;\n"
"")
        self.index.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.index.setObjectName("index")
        self.verticalLayout_2.addWidget(self.index)
        self.filepath = QtWidgets.QLabel(parent=self.info_widget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        self.filepath.setFont(font)
        self.filepath.setStyleSheet("color: rgb(242, 243, 245);\n"
"background-color: None;\n"
"padding: 1px;\n"
"")
        self.filepath.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.filepath.setObjectName("filepath")
        self.verticalLayout_2.addWidget(self.filepath)
        self.verticalLayout_4.addWidget(self.info_widget)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.folder_button, self.annotation_button)
        MainWindow.setTabOrder(self.annotation_button, self.prev_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.folder_button.setText(_translate("MainWindow", "Выбрать папку"))
        self.annotation_button.setText(_translate("MainWindow", "Выбрать аннотацию"))
        self.prev_button.setText(_translate("MainWindow", "<"))
        self.img.setText(_translate("MainWindow", "Image"))
        self.next_button.setText(_translate("MainWindow", ">"))
        self.index.setText(_translate("MainWindow", "TextLabel"))
        self.filepath.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
